const resource = {
	account: `حساب کاربری`,
	accept: "تایید",
	actions: "عملیات",
	add: "افزودن",
	again: "مجدد",
	address: "آدرس",
	admin: "مدیر",
	all: "همه",
	and: "و",
	answer: "پاسخ",
	answers: "پاسخ ها",
	answered: " پاسخ داده شده",
	back: "بازگشت",
	board: "تابلو",
	cancel: "لغو",
	city: "شهرستان",
	Check: "بررسی",
	change: "تغییر",
	closed: "بسته شده",
	code: "کد",
	complete: "تکمیل",
	count: "تعداد",
	create: "ایجاد",
	creator: "ایجاد کننده",
	contact: "تماس",
	changePasswordTip: "لطفا شماره همراه ای را که با آن ثبت نام کرده اید وارد نمایید",
	confirm: "تایید",
	checking: "درحال بررسی",
	customer: "مشتری",
	dashboard: "داشبورد",
	date: "تاریخ",
	description: "توضیحات",
	done: "شده",
	doyou: "آیا از",
	documents: "مدارک",
	dis: "عدم",
	edit: `ویرایش`,
	email: "ایمیل",
	enter: `ورود`,
	expecting: "انتظار",
	faq: "سوال متداول",
	fromatsOf: "فرمت های",
	fullDescriptions: "توضیحات تکمیلی ",
	faqs: "سوالات متداول",
	file: "فایل",
	for: "برای",
	forget: `فراموشی`,
	gender: "جنسیت",
	Grouping: `دسته بندی`,
	information: "اطلاعات",
	group: "گروه",
	given: "داده شده",
	in: "در",
	individual: `فردی`,
	internal: "داخلی",
	lastName: "نام خانوادگی",
	level: "سطح",
	list: "لیست",
	loading: "در حال بارگذاری...",
	mount: "میزان",
	marital: "تاهل",
	membership: "عضویت",
	nationalCode: "کد ملی",
	nationalCard: "کارت ملی",

	name: "نام",
	notdone: "نشده",
	notExist: "وجود ندارد",
	number: "شماره",
	next: "بعد",
	new: "جدید",
	notifications: "اعلانات",
	notification: "اعلان",
	notmember: `هنوز ثبت نام نکرده اید؟`,
	operator: "کارشناس",
	operators: "اپراتورها",
	partner: "شریک تجاری",
	password: `کلمه عبور`,
	pic: "تصویر",
	programm: "برنامه",
	phone: "شماره همراه",
	phoneNumber: "شماره همراه",
	post: "پست",
	priority: "اولویت",
	profile: "پروفایل",
	previous: "قبل",
	province: "استان",
	Personnel: "پرسنلی",
	quantity: "تعداد",
	question: "پرسش",
	rahkaran: "راهکاران",
	records: "سوابق",
	refer: "ارجاع",
	resetPasswordTip: "به شماره شما کدی ارسال گردید. لطفا پس از دریافت، کد را جهت تائید وارد نمایید",
	reject: "رد",
	registration: "ثبت",
	remove: "حذف",
	row: "ردیف",
	s: "ها",
	save: "ذخیره",
	score: "امتیاز",
	scoring: "امتیازدهی",
	see: "مشاهده",
	send: "ارسال",
	search: "جستجو",
	step: "مرحله",
	sure: "مطمئن هستید؟",
	set: "تعیین",
	selected: "انتخاب شد",
	selection: "انتخاب",
	seller: "فروشنده",
	support: "پشتیبانی",
	signupSuccessFullDone: "ثبت نام شما با موفقیت انجام شد",
	sentTo: "ارسال شده به",
	signUp: `ثبت نام`,
	signIn: `ورود`,
	show: "نمایش",
	specifications: `مشخصات`,
	status: "وضعیت",
	store: "فروشگاه",
	satisfication: "رضایت",
	ticket: "تیکت",
	tickets: "تیکت ها",
	title: "عنوان",
	to: `به`,
	undefined: "نامشخص",
	upload: "آپلود",
	uploaded: " آپلود شده",
	username: `نام کاربری`,
	users: "کاربران",
	user: "کاربر",
	visitor: "ویزیتور",
	voucher: "کوپن",
	y: "ی",

	colon: " : ",

	wellcome: "به خانواده بزرگ عالیس خوش آمدید",
	allRightsReserved: "تمامی حقوق طراحی متعلق به شرکت توسن پخش ستاره کیش میباشد",
	enterSignUpInformation: "لطفا جهت ثبت نام اطلاعات زیر را به درستی وارد نمایید",
	//
	apiMessage: {
		success: `تغییرات با موفقیت اعمال شد.`,
	},
	yup: {
		smsCodeDescription: "به شماره شما کدی ارسال گردید. لطفا پس از دریافت، کد را جهت تایید وارد نمایید.",

		phonNumberCount: `فرمت شماره همراه صحیح نمی باشد`,
		numberrequire: `وارد کردن شماره همراه الزامی است`,

		nationalcount: `کدملی باید 10 رقم باشد`,

		fNamerequire: ` وارد کردن نام الزامی است`,
		fNamemin: `نام باید بیشتر از 2 کاراکتر باشد`,

		lNamerequire: ` وارد کردن نام خانوادگی الزامی است`,
		lNamemin: `نام خانوادگی باید بیشتر از 3 کاراکتر باشد`,

		storeNamerequire: ` وارد کردن نام فروشگاه الزامی است`,
		storeNamemi: `نام فروشگاه باید بیشتر از 3 کاراکتر باشد`,

		provincerequire: ` وارد کردن استان الزامی است`,
		provincemi: `کد استان به درستی وارد نشده است`,

		cityrequire: ` وارد کردن شهر الزامی است`,
		citymi: `کد شهر به درستی وارد نشده است`,

		addressrequire: ` وارد کردن آدرس الزامی است`,
		addressmi: ` آدرس باید بیشتر از 15 کاراکتر باشد`,

		customerCoderequire: ` وارد کردن کد مشتری الزامی است`,
		customerCodemi: ` کد مشتری باید حداقل 5 کاراکتر باشد`,

		// numbermax:``,
		completeTheInformations: "برای ورود اطلاعات زیر را کامل کنید ",
		rulesAgreement: "با تمامی قوانین موافق هستم ",
		readRules: "خواندن قوانین",
		pleaseFullOutInformations: "لطفا جهت ثبت نام طلاعات زیر را به درستی وارد نمایید",

		addRating: "میزان رضایت شما از پاسخ دریافتی",
	},

	RhfErrors: {
		require: "پر کردن این بخش اجباری است",
		faqAnswerMin: "پاسخ باید حداقل 25 حرف باشد",
	},

	avatarName: "حسین سیدی",
};

export default resource;
